[32mINFO    [0m pytest_operator.plugin:plugin.py:903 Model status:

Model  Controller           Cloud/Region         Version  SLA          Timestamp
test   localhost-localhost  localhost/localhost  3.5.3    unsupported  02:39:21Z

App            Version  Status       Scale  Charm    Channel  Rev  Exposed  Message
config-server           maintenance    1/2  mongodb             0  no       installing MongoDB
shard-one               error          2/3  mongodb             1  no       hook failed: "install"
shard-two               waiting        0/1  mongodb             2  no       waiting for machine

Unit              Workload     Agent       Machine  Public address  Ports  Message
config-server/0*  maintenance  executing   0        10.17.185.27           (install) installing MongoDB
config-server/1   waiting      allocating  1        10.17.185.94           waiting for machine
shard-one/0       error        idle        2        10.17.185.81           hook failed: "install"
shard-one/1       waiting      allocating  3        10.17.185.240          agent initialising
shard-one/2*      maintenance  executing   4        10.17.185.61           (install) installing MongoDB
shard-two/0       waiting      allocating  5        10.17.185.49           waiting for machine

Machine  State    Address        Inst id        Base          AZ  Message
0        started  10.17.185.27   juju-f30fdc-0  ubuntu@22.04      Running
1        pending  10.17.185.94   juju-f30fdc-1  ubuntu@22.04      Running
2        started  10.17.185.81   juju-f30fdc-2  ubuntu@22.04      Running
3        started  10.17.185.240  juju-f30fdc-3  ubuntu@22.04      Running
4        started  10.17.185.61   juju-f30fdc-4  ubuntu@22.04      Running
5        pending  10.17.185.49   juju-f30fdc-5  ubuntu@22.04      Running

[32mINFO    [0m pytest_operator.plugin:plugin.py:909 Juju error logs:

machine-0: 02:38:42 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-0: 02:38:42 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-4: 02:38:42 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-4: 02:38:42 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-config-server-0: 02:38:42 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
unit-shard-one-2: 02:38:42 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-2: 02:38:48 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-2: 02:38:48 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-shard-one-0: 02:38:48 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-3: 02:38:59 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-3: 02:38:59 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-shard-one-1: 02:38:59 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
unit-shard-one-0: 02:39:20 ERROR unit.shard-one/0.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-shard-one-0/charm/lib/charms/operator_libs_linux/v2/snap.py", line 793, in _request_raw
    response = self.opener.open(request, timeout=self.timeout)
  File "/usr/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/usr/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 500: Internal Server Error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-shard-one-0/charm/lib/charms/operator_libs_linux/v2/snap.py", line 859, in __getitem__
    self._snap_map[snap_name] = self._load_info(snap_name)
  File "/var/lib/juju/agents/unit-shard-one-0/charm/lib/charms/operator_libs_linux/v2/snap.py", line 907, in _load_info
    info = self._snap_client.get_snap_information(name)
  File "/var/lib/juju/agents/unit-shard-one-0/charm/lib/charms/operator_libs_linux/v2/snap.py", line 815, in get_snap_information
    return self._request("GET", "find", {"name": name})[0]
  File "/var/lib/juju/agents/unit-shard-one-0/charm/lib/charms/operator_libs_linux/v2/snap.py", line 772, in _request
    response = self._request_raw(method, path, query, headers, data)
  File "/var/lib/juju/agents/unit-shard-one-0/charm/lib/charms/operator_libs_linux/v2/snap.py", line 804, in _request_raw
    raise SnapAPIError(body, code, status, message)
charms.operator_libs_linux.v2.snap.SnapAPIError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-shard-one-0/charm/./src/charm.py", line 1598, in <module>
    main(MongodbOperatorCharm)
  File "/var/lib/juju/agents/unit-shard-one-0/charm/venv/ops/main.py", line 551, in main
    manager.run()
  File "/var/lib/juju/agents/unit-shard-one-0/charm/venv/ops/main.py", line 530, in run
    self._emit()
  File "/var/lib/juju/agents/unit-shard-one-0/charm/venv/ops/main.py", line 519, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name)
  File "/var/lib/juju/agents/unit-shard-one-0/charm/venv/ops/main.py", line 147, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-shard-one-0/charm/venv/ops/framework.py", line 348, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-shard-one-0/charm/venv/ops/framework.py", line 860, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-shard-one-0/charm/venv/ops/framework.py", line 950, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-shard-one-0/charm/./src/charm.py", line 378, in _on_install
    self.install_snap_packages(packages=Config.SNAP_PACKAGES)
  File "/var/lib/juju/agents/unit-shard-one-0/charm/./src/charm.py", line 1060, in install_snap_packages
    snap_package = snap_cache[snap_name]
  File "/var/lib/juju/agents/unit-shard-one-0/charm/lib/charms/operator_libs_linux/v2/snap.py", line 861, in __getitem__
    raise SnapNotFoundError("Snap '{}' not found!".format(snap_name))
charms.operator_libs_linux.v2.snap.SnapNotFoundError: Snap 'charmed-mongodb' not found!

[32mINFO    [0m pytest_operator.plugin:plugin.py:991 Forgetting model main...