{"uid":"fe844393239cbf8d","name":"test_scale_up_down","fullName":"tests.integration.ha_tests.test_ha#test_scale_up_down","historyId":"45176ae3925cc8b3ce1968c46f898dea","time":{"start":1739672152665,"stop":1739674097366,"duration":1944701},"description":"Scale up and down the application and verify the replica set is healthy.","descriptionHtml":"<p>Scale up and down the application and verify the replica set is healthy.</p>\n","status":"broken","statusMessage":"asyncio.exceptions.TimeoutError: Timed out waiting for model:\n  mongodb/17 [allocating] waiting: agent initialising","statusTrace":"Traceback (most recent call last):\n  File \"/home/ubuntu/actions-runner/_work/mongodb-operator/mongodb-operator/.tox/integration/lib/python3.10/site-packages/_pytest/runner.py\", line 341, in from_call\n    result: TResult | None = func()\n  File \"/home/ubuntu/actions-runner/_work/mongodb-operator/mongodb-operator/.tox/integration/lib/python3.10/site-packages/_pytest/runner.py\", line 242, in <lambda>\n    lambda: runtest_hook(item=item, **kwds), when=when, reraise=reraise\n  File \"/home/ubuntu/actions-runner/_work/mongodb-operator/mongodb-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_hooks.py\", line 513, in __call__\n    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)\n  File \"/home/ubuntu/actions-runner/_work/mongodb-operator/mongodb-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_manager.py\", line 120, in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n  File \"/home/ubuntu/actions-runner/_work/mongodb-operator/mongodb-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 182, in _multicall\n    return outcome.get_result()\n  File \"/home/ubuntu/actions-runner/_work/mongodb-operator/mongodb-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_result.py\", line 100, in get_result\n    raise exc.with_traceback(exc.__traceback__)\n  File \"/home/ubuntu/actions-runner/_work/mongodb-operator/mongodb-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/home/ubuntu/actions-runner/_work/mongodb-operator/mongodb-operator/.tox/integration/lib/python3.10/site-packages/_pytest/threadexception.py\", line 92, in pytest_runtest_call\n    yield from thread_exception_runtest_hook()\n  File \"/home/ubuntu/actions-runner/_work/mongodb-operator/mongodb-operator/.tox/integration/lib/python3.10/site-packages/_pytest/threadexception.py\", line 68, in thread_exception_runtest_hook\n    yield\n  File \"/home/ubuntu/actions-runner/_work/mongodb-operator/mongodb-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/home/ubuntu/actions-runner/_work/mongodb-operator/mongodb-operator/.tox/integration/lib/python3.10/site-packages/_pytest/unraisableexception.py\", line 95, in pytest_runtest_call\n    yield from unraisable_exception_runtest_hook()\n  File \"/home/ubuntu/actions-runner/_work/mongodb-operator/mongodb-operator/.tox/integration/lib/python3.10/site-packages/_pytest/unraisableexception.py\", line 70, in unraisable_exception_runtest_hook\n    yield\n  File \"/home/ubuntu/actions-runner/_work/mongodb-operator/mongodb-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/home/ubuntu/actions-runner/_work/mongodb-operator/mongodb-operator/.tox/integration/lib/python3.10/site-packages/_pytest/logging.py\", line 846, in pytest_runtest_call\n    yield from self._runtest_for(item, \"call\")\n  File \"/home/ubuntu/actions-runner/_work/mongodb-operator/mongodb-operator/.tox/integration/lib/python3.10/site-packages/_pytest/logging.py\", line 829, in _runtest_for\n    yield\n  File \"/home/ubuntu/actions-runner/_work/mongodb-operator/mongodb-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/home/ubuntu/actions-runner/_work/mongodb-operator/mongodb-operator/.tox/integration/lib/python3.10/site-packages/_pytest/capture.py\", line 880, in pytest_runtest_call\n    return (yield)\n  File \"/home/ubuntu/actions-runner/_work/mongodb-operator/mongodb-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/home/ubuntu/actions-runner/_work/mongodb-operator/mongodb-operator/.tox/integration/lib/python3.10/site-packages/_pytest/skipping.py\", line 257, in pytest_runtest_call\n    return (yield)\n  File \"/home/ubuntu/actions-runner/_work/mongodb-operator/mongodb-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"/home/ubuntu/actions-runner/_work/mongodb-operator/mongodb-operator/.tox/integration/lib/python3.10/site-packages/_pytest/runner.py\", line 174, in pytest_runtest_call\n    item.runtest()\n  File \"/home/ubuntu/actions-runner/_work/mongodb-operator/mongodb-operator/.tox/integration/lib/python3.10/site-packages/_pytest/python.py\", line 1627, in runtest\n    self.ihook.pytest_pyfunc_call(pyfuncitem=self)\n  File \"/home/ubuntu/actions-runner/_work/mongodb-operator/mongodb-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_hooks.py\", line 513, in __call__\n    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)\n  File \"/home/ubuntu/actions-runner/_work/mongodb-operator/mongodb-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_manager.py\", line 120, in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n  File \"/home/ubuntu/actions-runner/_work/mongodb-operator/mongodb-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 182, in _multicall\n    return outcome.get_result()\n  File \"/home/ubuntu/actions-runner/_work/mongodb-operator/mongodb-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_result.py\", line 100, in get_result\n    raise exc.with_traceback(exc.__traceback__)\n  File \"/home/ubuntu/actions-runner/_work/mongodb-operator/mongodb-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"/home/ubuntu/actions-runner/_work/mongodb-operator/mongodb-operator/.tox/integration/lib/python3.10/site-packages/_pytest/python.py\", line 159, in pytest_pyfunc_call\n    result = testfunction(**testargs)\n  File \"/home/ubuntu/actions-runner/_work/mongodb-operator/mongodb-operator/.tox/integration/lib/python3.10/site-packages/pytest_asyncio/plugin.py\", line 529, in inner\n    _loop.run_until_complete(task)\n  File \"/usr/lib/python3.10/asyncio/base_events.py\", line 649, in run_until_complete\n    return future.result()\n  File \"/home/ubuntu/actions-runner/_work/mongodb-operator/mongodb-operator/tests/integration/ha_tests/test_ha.py\", line 780, in test_scale_up_down\n    await scale_and_verify(ops_test, count=count)\n  File \"/home/ubuntu/actions-runner/_work/mongodb-operator/mongodb-operator/tests/integration/ha_tests/helpers.py\", line 720, in scale_and_verify\n    await ops_test.model.wait_for_idle(\n  File \"/home/ubuntu/actions-runner/_work/mongodb-operator/mongodb-operator/.tox/integration/lib/python3.10/site-packages/juju/model/__init__.py\", line 3250, in wait_for_idle\n    raise asyncio.TimeoutError(\nasyncio.exceptions.TimeoutError: Timed out waiting for model:\n  mongodb/17 [allocating] waiting: agent initialising","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":1,"retriesStatusChange":true,"beforeStages":[{"name":"event_loop","time":{"start":1739669485098,"stop":1739669485099,"duration":1},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"tmp_path_factory","time":{"start":1739669485099,"stop":1739669485099,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"ops_test","time":{"start":1739669485099,"stop":1739669485236,"duration":137},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"continuous_writes","time":{"start":1739672150617,"stop":1739672152664,"duration":2047},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"abort_on_fail","time":{"start":1739672150617,"stop":1739672150617,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"testStage":{"description":"Scale up and down the application and verify the replica set is healthy.","status":"broken","statusMessage":"asyncio.exceptions.TimeoutError: Timed out waiting for model:\n  mongodb/17 [allocating] waiting: agent initialising","statusTrace":"Traceback (most recent call last):\n  File \"/home/ubuntu/actions-runner/_work/mongodb-operator/mongodb-operator/.tox/integration/lib/python3.10/site-packages/_pytest/runner.py\", line 341, in from_call\n    result: TResult | None = func()\n  File \"/home/ubuntu/actions-runner/_work/mongodb-operator/mongodb-operator/.tox/integration/lib/python3.10/site-packages/_pytest/runner.py\", line 242, in <lambda>\n    lambda: runtest_hook(item=item, **kwds), when=when, reraise=reraise\n  File \"/home/ubuntu/actions-runner/_work/mongodb-operator/mongodb-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_hooks.py\", line 513, in __call__\n    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)\n  File \"/home/ubuntu/actions-runner/_work/mongodb-operator/mongodb-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_manager.py\", line 120, in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n  File \"/home/ubuntu/actions-runner/_work/mongodb-operator/mongodb-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 182, in _multicall\n    return outcome.get_result()\n  File \"/home/ubuntu/actions-runner/_work/mongodb-operator/mongodb-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_result.py\", line 100, in get_result\n    raise exc.with_traceback(exc.__traceback__)\n  File \"/home/ubuntu/actions-runner/_work/mongodb-operator/mongodb-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/home/ubuntu/actions-runner/_work/mongodb-operator/mongodb-operator/.tox/integration/lib/python3.10/site-packages/_pytest/threadexception.py\", line 92, in pytest_runtest_call\n    yield from thread_exception_runtest_hook()\n  File \"/home/ubuntu/actions-runner/_work/mongodb-operator/mongodb-operator/.tox/integration/lib/python3.10/site-packages/_pytest/threadexception.py\", line 68, in thread_exception_runtest_hook\n    yield\n  File \"/home/ubuntu/actions-runner/_work/mongodb-operator/mongodb-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/home/ubuntu/actions-runner/_work/mongodb-operator/mongodb-operator/.tox/integration/lib/python3.10/site-packages/_pytest/unraisableexception.py\", line 95, in pytest_runtest_call\n    yield from unraisable_exception_runtest_hook()\n  File \"/home/ubuntu/actions-runner/_work/mongodb-operator/mongodb-operator/.tox/integration/lib/python3.10/site-packages/_pytest/unraisableexception.py\", line 70, in unraisable_exception_runtest_hook\n    yield\n  File \"/home/ubuntu/actions-runner/_work/mongodb-operator/mongodb-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/home/ubuntu/actions-runner/_work/mongodb-operator/mongodb-operator/.tox/integration/lib/python3.10/site-packages/_pytest/logging.py\", line 846, in pytest_runtest_call\n    yield from self._runtest_for(item, \"call\")\n  File \"/home/ubuntu/actions-runner/_work/mongodb-operator/mongodb-operator/.tox/integration/lib/python3.10/site-packages/_pytest/logging.py\", line 829, in _runtest_for\n    yield\n  File \"/home/ubuntu/actions-runner/_work/mongodb-operator/mongodb-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/home/ubuntu/actions-runner/_work/mongodb-operator/mongodb-operator/.tox/integration/lib/python3.10/site-packages/_pytest/capture.py\", line 880, in pytest_runtest_call\n    return (yield)\n  File \"/home/ubuntu/actions-runner/_work/mongodb-operator/mongodb-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/home/ubuntu/actions-runner/_work/mongodb-operator/mongodb-operator/.tox/integration/lib/python3.10/site-packages/_pytest/skipping.py\", line 257, in pytest_runtest_call\n    return (yield)\n  File \"/home/ubuntu/actions-runner/_work/mongodb-operator/mongodb-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"/home/ubuntu/actions-runner/_work/mongodb-operator/mongodb-operator/.tox/integration/lib/python3.10/site-packages/_pytest/runner.py\", line 174, in pytest_runtest_call\n    item.runtest()\n  File \"/home/ubuntu/actions-runner/_work/mongodb-operator/mongodb-operator/.tox/integration/lib/python3.10/site-packages/_pytest/python.py\", line 1627, in runtest\n    self.ihook.pytest_pyfunc_call(pyfuncitem=self)\n  File \"/home/ubuntu/actions-runner/_work/mongodb-operator/mongodb-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_hooks.py\", line 513, in __call__\n    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)\n  File \"/home/ubuntu/actions-runner/_work/mongodb-operator/mongodb-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_manager.py\", line 120, in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n  File \"/home/ubuntu/actions-runner/_work/mongodb-operator/mongodb-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 182, in _multicall\n    return outcome.get_result()\n  File \"/home/ubuntu/actions-runner/_work/mongodb-operator/mongodb-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_result.py\", line 100, in get_result\n    raise exc.with_traceback(exc.__traceback__)\n  File \"/home/ubuntu/actions-runner/_work/mongodb-operator/mongodb-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"/home/ubuntu/actions-runner/_work/mongodb-operator/mongodb-operator/.tox/integration/lib/python3.10/site-packages/_pytest/python.py\", line 159, in pytest_pyfunc_call\n    result = testfunction(**testargs)\n  File \"/home/ubuntu/actions-runner/_work/mongodb-operator/mongodb-operator/.tox/integration/lib/python3.10/site-packages/pytest_asyncio/plugin.py\", line 529, in inner\n    _loop.run_until_complete(task)\n  File \"/usr/lib/python3.10/asyncio/base_events.py\", line 649, in run_until_complete\n    return future.result()\n  File \"/home/ubuntu/actions-runner/_work/mongodb-operator/mongodb-operator/tests/integration/ha_tests/test_ha.py\", line 780, in test_scale_up_down\n    await scale_and_verify(ops_test, count=count)\n  File \"/home/ubuntu/actions-runner/_work/mongodb-operator/mongodb-operator/tests/integration/ha_tests/helpers.py\", line 720, in scale_and_verify\n    await ops_test.model.wait_for_idle(\n  File \"/home/ubuntu/actions-runner/_work/mongodb-operator/mongodb-operator/.tox/integration/lib/python3.10/site-packages/juju/model/__init__.py\", line 3250, in wait_for_idle\n    raise asyncio.TimeoutError(\nasyncio.exceptions.TimeoutError: Timed out waiting for model:\n  mongodb/17 [allocating] waiting: agent initialising","steps":[],"attachments":[{"uid":"e8407972f18c720c","name":"log","source":"e8407972f18c720c.txt","type":"text/plain","size":17561}],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":1,"hasContent":true,"attachmentStep":false},"afterStages":[{"name":"continuous_writes::finalizer","time":{"start":1739674097369,"stop":1739674101637,"duration":4268},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"abort_on_fail::0","time":{"start":1739674101637,"stop":1739674101637,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"ops_test::finalizer","time":{"start":1739674101641,"stop":1739674102193,"duration":552},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"event_loop::2","time":{"start":1739674102194,"stop":1739674102194,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"event_loop::_close_event_loop","time":{"start":1739674102194,"stop":1739674102194,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"event_loop::_provide_clean_event_loop","time":{"start":1739674102194,"stop":1739674102194,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"labels":[{"name":"tag","value":"unstable"},{"name":"tag","value":"abort_on_fail"},{"name":"tag","value":"group(1)"},{"name":"tag","value":"runner(['self-hosted', 'linux', 'X64', 'jammy', 'large'])"},{"name":"tag","value":"asyncio"},{"name":"parentSuite","value":"tests.integration.ha_tests"},{"name":"suite","value":"test_ha"},{"name":"host","value":"github-runner"},{"name":"thread","value":"30609-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.integration.ha_tests.test_ha"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[{"uid":"9e7ae1794aa0806e","status":"unknown","time":{}}],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"history":{"statistic":{"failed":0,"broken":116,"skipped":22,"passed":32,"unknown":7,"total":177},"items":[{"uid":"5470fb402c39d09b","reportUrl":"../2615//#testresult/5470fb402c39d09b","status":"broken","statusDetails":"asyncio.exceptions.TimeoutError: Timed out waiting for model:\n  mongodb/17 [allocating] waiting: agent initialising","time":{"start":1739585661288,"stop":1739587245176,"duration":1583888}},{"uid":"48a5649a7c370a9f","reportUrl":"../2614//#testresult/48a5649a7c370a9f","status":"broken","statusDetails":"asyncio.exceptions.TimeoutError: Timed out waiting for model:\n  mongodb/17 [allocating] waiting: agent initialising","time":{"start":1739500332880,"stop":1739502507546,"duration":2174666}},{"uid":"85fc0c76739d413a","reportUrl":"../2613//#testresult/85fc0c76739d413a","status":"broken","statusDetails":"asyncio.exceptions.TimeoutError: Timed out waiting for model:\n  mongodb/17 [allocating] waiting: agent initialising","time":{"start":1739413295316,"stop":1739414956229,"duration":1660913}},{"uid":"9f3a165b39abc8a4","reportUrl":"../2603//#testresult/9f3a165b39abc8a4","status":"broken","statusDetails":"asyncio.exceptions.TimeoutError: Timed out waiting for model:\nmongodb/17 [allocating] waiting: agent initialising","time":{"start":1739239328447,"stop":1739240828265,"duration":1499818}},{"uid":"7d73f412aa0667b4","reportUrl":"../2589//#testresult/7d73f412aa0667b4","status":"broken","statusDetails":"asyncio.exceptions.TimeoutError: Timed out waiting for model:\nmongodb/17 [allocating] waiting: agent initialising","time":{"start":1739152926333,"stop":1739154438525,"duration":1512192}},{"uid":"4ca7255b355b1e8d","reportUrl":"../2588//#testresult/4ca7255b355b1e8d","status":"broken","statusDetails":"asyncio.exceptions.TimeoutError: Timed out waiting for model:\nmongodb/17 [allocating] waiting: agent initialising","time":{"start":1739067439660,"stop":1739069057240,"duration":1617580}},{"uid":"69e472863b0f9791","reportUrl":"../2587//#testresult/69e472863b0f9791","status":"broken","statusDetails":"asyncio.exceptions.TimeoutError: Timed out waiting for model:\nmongodb/17 [allocating] waiting: agent initialising","time":{"start":1738980118140,"stop":1738981661502,"duration":1543362}},{"uid":"de21111df548c665","reportUrl":"../2579//#testresult/de21111df548c665","status":"broken","statusDetails":"asyncio.exceptions.TimeoutError: Timed out waiting for model:\nmongodb/17 [allocating] waiting: agent initialising","time":{"start":1738895635244,"stop":1738898228803,"duration":2593559}},{"uid":"317244a6d7c0394c","reportUrl":"../2576//#testresult/317244a6d7c0394c","status":"broken","statusDetails":"asyncio.exceptions.TimeoutError: Timed out waiting for model:\nmongodb/17 [allocating] waiting: agent initialising","time":{"start":1738807330538,"stop":1738808851694,"duration":1521156}},{"uid":"8e648b767120eade","reportUrl":"../2570//#testresult/8e648b767120eade","status":"broken","statusDetails":"asyncio.exceptions.TimeoutError: Timed out waiting for model:\nmongodb/17 [allocating] waiting: agent initialising","time":{"start":1738721786589,"stop":1738723360876,"duration":1574287}},{"uid":"113da5c9986abbe0","reportUrl":"../2562//#testresult/113da5c9986abbe0","status":"broken","statusDetails":"asyncio.exceptions.TimeoutError: Timed out waiting for model:\nmongodb/17 [allocating] waiting: agent initialising","time":{"start":1738635453645,"stop":1738636985773,"duration":1532128}},{"uid":"645424ab4efdd396","reportUrl":"../2559//#testresult/645424ab4efdd396","status":"broken","statusDetails":"asyncio.exceptions.TimeoutError: Timed out waiting for model:\nmongodb/17 [allocating] waiting: agent initialising","time":{"start":1738550089983,"stop":1738552193871,"duration":2103888}},{"uid":"9e9fa612e1776b30","reportUrl":"../2558//#testresult/9e9fa612e1776b30","status":"broken","statusDetails":"asyncio.exceptions.TimeoutError: Timed out waiting for model:\nmongodb/17 [allocating] waiting: agent initialising","time":{"start":1738462775625,"stop":1738465262957,"duration":2487332}},{"uid":"2ae402cdf59d3038","reportUrl":"../2557//#testresult/2ae402cdf59d3038","status":"broken","statusDetails":"asyncio.exceptions.TimeoutError: Timed out waiting for model:\nmongodb/17 [allocating] waiting: agent initialising","time":{"start":1738376210301,"stop":1738377782745,"duration":1572444}},{"uid":"118a1d42598c4c91","reportUrl":"../2548//#testresult/118a1d42598c4c91","status":"broken","statusDetails":"asyncio.exceptions.TimeoutError: Timed out waiting for model:\nmongodb/17 [allocating] waiting: agent initialising","time":{"start":1738288932382,"stop":1738290431941,"duration":1499559}},{"uid":"24a944a31f0c3485","reportUrl":"../2543//#testresult/24a944a31f0c3485","status":"skipped","statusDetails":"XFAIL reason: aborted\n\n_pytest.outcomes.XFailed: aborted","time":{"start":1738203057266,"stop":1738203057266,"duration":0}},{"uid":"a6dac430ac2f9e88","reportUrl":"../2540//#testresult/a6dac430ac2f9e88","status":"broken","statusDetails":"asyncio.exceptions.TimeoutError: Timed out waiting for model:\nmongodb/17 [allocating] waiting: agent initialising","time":{"start":1738116208381,"stop":1738117718478,"duration":1510097}},{"uid":"894bf2213ebb7a9e","reportUrl":"../2537//#testresult/894bf2213ebb7a9e","status":"broken","statusDetails":"asyncio.exceptions.TimeoutError: Timed out waiting for model:\nmongodb/17 [allocating] waiting: agent initialising","time":{"start":1738031663734,"stop":1738034027078,"duration":2363344}},{"uid":"cd4f136ce45b2551","reportUrl":"../2532//#testresult/cd4f136ce45b2551","status":"broken","statusDetails":"asyncio.exceptions.TimeoutError: Timed out waiting for model:\nmongodb/17 [allocating] waiting: agent initialising","time":{"start":1737944269249,"stop":1737945818384,"duration":1549135}},{"uid":"f440675f8f14a304","reportUrl":"../2531//#testresult/f440675f8f14a304","status":"broken","statusDetails":"asyncio.exceptions.TimeoutError: Timed out waiting for model:\nmongodb/17 [allocating] waiting: agent initialising","time":{"start":1737857810158,"stop":1737859350447,"duration":1540289}}]},"tags":["unstable","runner(['self-hosted', 'linux', 'X64', 'jammy', 'large'])","asyncio","abort_on_fail","group(1)"]},"source":"fe844393239cbf8d.json","parameterValues":[]}